language: julia
dist: xenial

os:
  - linux
  - osx

# requires MacOS 10.14
osx_image: xcode11.4

julia:
  - 1.3
  - 1.4
  - nightly

branches:
  only:
    - master
    - /^release-.*/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email: false

cache:
  apt: true
  directories:
    - $HOME/.cache
    - $HOME/.ccache
    - $HOME/.julia/registries # can we cache all of .julia?
    - $HOME/.julia/artifacts

addons:
  apt:
    packages:
    - gfortran

env:
  global:
    - SPACK_ROOT: $HOME/.cache/spack
    - PATH: $PATH:$HOME/.cache/spack/bin
  jobs:
    - MPI_IMPL=mpich
      JULIA_MPI_BINARY=system
    - MPI_IMPL=openmpi
      JULIA_MPI_BINARY=system
      JULIA_MPIEXEC_TEST_ARGS="--oversubscribe"

jobs:
  allow_failures: # issue 262
  - julia: nightly
  - os: osx
    env: MPI_IMPL=openmpi
  exclude:
  - os: osx
    env: MPI_IMPL=intelmpi JULIA_MPI_BINARY=system
  include:
    - stage: "Coverage"
      julia: 1.4
      os: linux
      after_success: # Intentionally rerun tests
        - julia -e 'using Pkg; cd(Pkg.dir("MPI")); Pkg.add("Coverage")'
        - julia -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'
        - julia -e 'using Coverage; Codecov.submit(Codecov.process_folder())'

before_install:
  - |
    if ! which spack >/dev/null; then
      mkdir -p $SPACK_ROOT &&
      git clone --depth 50 https://github.com/spack/spack.git $SPACK_ROOT &&
      printf "config:\n  build_jobs: 2\n" > $SPACK_ROOT/etc/spack/config.yaml &&
      printf "packages:\n  all:\n    target: ['x86_64']\n" > $SPACK_ROOT/etc/spack/packages.yaml;
    fi
  - travis_wait spack install $MPI_IMPL
  - spack clean -a
  - source $SPACK_ROOT/share/spack/setup-env.sh
  - spack load $MPI_IMPL

